name: Autograde

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Bash Tests
        run: bash tests.sh
